{% set version = "3.0.3" %}

package:
  name: libjpeg-turbo
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
  sha256: a649205a90e39a548863a3614a9576a3fb4465f8e8e66d54999f127957c25b21

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    # https://github.com/libjpeg-turbo/libjpeg-turbo/blob/7fa4b5b762c9a99b46b0b7838f5fd55071b92ea5/BUILDING.md?plain=1#L16
    - yasm >=1.2.0
    - jom  # [win]
    - make # [not win]
  run_constrained:
    - jpeg <0.0.0a

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.libjpeg-turbo.org/
  license: IJG AND BSD-3-Clause AND Zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations
  dev_url: https://github.com/libjpeg-turbo/libjpeg-turbo

extra:
  recipe-maintainers:
    - valgur
    - sdvillal
    - carlodri
    - hmaarrfk
