# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YviW8frkLxenczZOFCdEUeh0hz/Hn/zNnQ1brYtgcDqnW6XecSXo7pO3K1+ODpGe5JWosrqV1D28AOKErre9oEVfyCGP2bySwRYxoqwHjtw2KzOoytPQan2sD3IUC21vFiOsOMDseelgNoTF3clqF7vN3/fdNaOgphHsi8Ivmb5qXRfU4/KpuJj2RoTi0YRwuMv75LD16J/zFieR/kx7huamWHESZUrDCZDjuH7A3PadehSDCv9hAzw6jOTgnPSw3W621bBT/Y3nePc+jPOmZg0wIA8ulX8JfSMkbxdlZnWX0D2j3cNnS+4+233l6dIiRFJcPOviuKYq4+EbagVR1/af8DLsk5TvBqcd876XfWKEUt1NXwAdRWVb1kgjyowQTUgLUFWxQPyxz3a5N6lM/qgyA8U1gKISbKPG3ieoYqAUYqPthOKybZAKJtzk/+UfzCmsYP4RWQ1ykXHu0zhl0v4WL3C3KB97SjyV5jBeB/WSs5l9mYidd8o43cKzCXFYtKXUWRt3WT4cTfMrMrZqBV8bTMc+EvDklkW1V4jzalBATaMh7A05sWMOrnCXO3+0LGetcY4iPsPFZLy2+a1xHOQANq/yNoHCPFjE4teqTDJ4uXHs6WO/ZZ9bMme2LMkedTUYlJ/xb5G0qEC52zuEqvOgiCWPg34y8VSpQMTMH6k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
