travis:
  secure:
    BINSTAR_TOKEN: gpfbVDo8JbOdoCYmAN4mBCzi3EI6wGGa7R9LcguSaMpHe4zFJz2FMXJwIr57/1c84ZcmPkyTdwPA0+GhnynJacWjR/xURNgPfjCmtdOu61VvS28AaLG9/Tb9QrNHH1hXQP3vyp7X+dLHzALjM+ml0k97u8ONfU9cyp8Gdooi4gbTxIPquyltRBPU+9GOG8trcHyNk27GVPMjB3V6GIUnClzSZPTPDOkeCh9ViKyJA3KqRt/x1+mesYm/iU6mNwB1qUPwqB76ONXVAUfr97w2CMl1zANKZcUfOFRSnksF7gIfguZPCgPNQtSUQZYBKkn1P5DB2n+TBwteQrfZCPtb87s1g4QzP5emNnPvb6np2VKTEH6vXllORJVVPJNce14kaJIZC8iy0Pvd9ikO5YdfXtW+y1z/ksqkeztOnydnSznDw/TRP4OwK+Vsd/7SdYNhnWxQC9ekdaKcXzlB87BnKomMKekxMrmIT0a3w09+A/M4GnPOCVZ2TTgssKm6cP+cAQUloOFjKuvGaH4EyQwCN0FgwWvfOZp7xruweMRsrZpGMRHiEO5Jz1Gmo1so1Q8rV3j/9hJxHG9wnVwwrk6HFxygx+3MGOvxBuFniisCZb9YmcndoNsferXH6kkKZdvWBJhualtvkHUYiOLNmoCLNMTxnTPg5mD0Vi3N+zCa+5s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
